name: ðŸš€ Payments release

on:
  push:
    branches:
      - develop
      - uat
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'
  workflow_dispatch:

jobs:
  payments-flow-release:
    runs-on: ubuntu-22.04
    steps:
      - name: ðŸ”– Checkout code
        # https://github.com/actions/checkout/releases/tag/v4.2.1
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          ref: ${{ github.ref_name }}

      - name: ðŸš€ release + docker + azdo
        # https://github.com/pagopa/github-actions-template/releases/tag/v1.19.1
        uses: pagopa/github-actions-template/payments-flow-release@3ae6a4268ccff000194696b21e1124d9e8ddf997
        with:
          current_branch: ${{ github.ref_name }}
